POST https://care-for-animals-backend.onrender.com/app/signup
Content-Type:  application/json

{
    "fullName" : "chiranjeevi",
    "userName" : "chiru",
    "email" : "mvschiranjeevi@gmail.com",
    "password" : "chiru123"
}